sonar.projectKey=assessment-platform-web-ui
sonar.projectName=Assessment Platform Web UI
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8